<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_form' => [[], ['_controller' => 'App\\Controller\\FormController::index'], [], [['text', '/']], [], [], []],
    'app_form_success' => [[], ['_controller' => 'App\\Controller\\FormController::success'], [], [['text', '/success']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
    'app_admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminController::dashboard'], [], [['text', '/admin']], [], [], []],
    'app_admin_submissions' => [[], ['_controller' => 'App\\Controller\\AdminController::submissions'], [], [['text', '/admin/submissions']], [], [], []],
    'app_admin_submission_view' => [['id'], ['_controller' => 'App\\Controller\\AdminController::viewSubmission'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/submission']], [], [], []],
    'app_admin_users' => [[], ['_controller' => 'App\\Controller\\AdminController::users'], [], [['text', '/admin/users']], [], [], []],
    'app_admin_user_new' => [[], ['_controller' => 'App\\Controller\\AdminController::newUser'], [], [['text', '/admin/users/new']], [], [], []],
];
